### ISSUE TITLE
When training with the GL18 dataset, what is the whitening dataset?

### ISSUE THREAD

**Issue by peternara** [tonyngjichun/SOLAR#7]
Hi, @tonyngjichun 

When training with the GL18 dataset, what is the whitening dataset?

Did you ever use "retrieval-SfM-120k-whiten.pkl" from the sfm-120k dataset?
  When whitening, it's not clear, but in your code it looks like you're using "retrieval-SfM-120k-whiten.pkl", not the GL18 dataset. right?  (https://github.com/tonyngjichun/SOLAR/blob/852a95fe64d94ab95cc280e0cf68c69a2d6dd7d8/solar_global/examples/train.py#L659)
 
thanks

**Comment by tonyngjichun** [comment]
Hi, thanks for the question

The model in our paper use end-to-end whitening, i.e. the whitening linear layer is learnt during training. Therefore the `test_whiten` option is not needed during test time. Otherwise before training we load the pre-trained whitening layer (https://github.com/tonyngjichun/SOLAR/blob/852a95fe64d94ab95cc280e0cf68c69a2d6dd7d8/solar_global/networks/imageretrievalnet.py#L70) and fine-tune from it

**Comment by peternara** [comment]
Thanks for your quick reply.
That part seems to be using the filip code model as it is.

https://github.com/tonyngjichun/SOLAR/blob/852a95fe64d94ab95cc280e0cf68c69a2d6dd7d8/solar_global/networks/imageretrievalnet.py#L70

Does this mean you don't know which dataset is used?  (There is no mention of this in the filip code.)

thanks

**Comment by tonyngjichun** [comment]
This is the pretrained whitening weights - both trained using SfM120k and GL18 are available in Filip's code. From what I remember, it doesn't really matter which pretrained weights are used for initialisation as long as the model is fine-tuned on GL18. Hope this helps!
